# Assignment-1: Transformations and representations

Team Name: kemonache

Roll number: 2019102034 and 2019102040

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

In [27]:
import open3d as o3d
import numpy as np
import copy

# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.
2. Convert the mesh to a point cloud and change the colour of points.
3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.
4. Scale, Transform, and Rotate the rabbit (visualise after each step).
5. Save the point cloud as bunny.pcd.

In [28]:
#1
print("Visualising point cloud.....")
bunny = o3d.io.read_point_cloud("data/bunny.ply")
o3d.visualization.draw_geometries([bunny])

print("Visualising mesh.....")
mesh = o3d.io.read_triangle_mesh("data/bunny.ply")
o3d.visualization.draw_geometries([mesh])

#2
print("Converting to point cloud and visualising")
bny = mesh.sample_points_uniformly(40000) 
bny.paint_uniform_color([1,215/255,0])              #Let's make the bunny golden
o3d.visualization.draw_geometries([bny])

#3
def custom_draw_geometry_with_custom_fov(bunny, fov_step):
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(bunny)
    ctr = vis.get_view_control()
    ctr.change_field_of_view(step=fov_step)
    vis.run()
    vis.destroy_window()

new_angle = 85   #Enter the new angle here
custom_draw_geometry_with_custom_fov(bunny,new_angle-60)            
#We need to substract 60 because change_field_of_view works by adding 60 degrees to given angle so we set an offset

mesh_frame =  o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.01,origin=[0,0,0])
o3d.visualization.draw_geometries([bunny,mesh_frame])

#4

#Scale
scaling_factor = 3
bunny_scaled = copy.deepcopy(bunny).scale(scaling_factor,center=bunny.get_center())
o3d.visualization.draw_geometries([bunny_scaled])

#Rotate
x = np.pi/2     #Set angle of rotation in x
y = np.pi/2     #Set angle of rotation in y
z = 0           #Set angle of rotation in z

R = bunny.get_rotation_matrix_from_xyz((x,y,z))
print("Rotation Matrix: ")
print(R)
bunny_rotate = copy.deepcopy(bunny).rotate(R)
o3d.visualization.draw_geometries([bunny_rotate])

#Transform

Rx = np.pi/2     #Set angle of rotation in Rx
Ry = np.pi/2     #Set angle of rotation in Ry
Rz = 0           #Set angle of rotation in Rz
R = bunny.get_rotation_matrix_from_xyz((Rx,Ry,Rz))  #Rotational part of Transform

Tx = 1           #Set value of translation in Tx
Ty = 0           #Set value of translation in Ty
Tz = 2.5         #Set value of translation in Tz
P_borg = np.array([[Tx],[Ty],[Tz]])                   #Translational part of Transform

T = np.eye(4)    #Transform Matrix
T[0:3,0:3] = R
T[0:3,3:] = P_borg
print("Transformation Matrix: ")
print(T)
bunny_transform = copy.deepcopy(bunny).transform(T)
o3d.visualization.draw_geometries([bunny_transform])


#Visualise everyone together
bunny.paint_uniform_color([1,1,1])               #Original Bunny in white
bunny_scaled.paint_uniform_color([1,0,0])        #Scaled Bunny in red
bunny_rotate.paint_uniform_color([0,1,0])        #Rotated Bunny in green
bunny_transform.paint_uniform_color([0,0,1])     #Transformed Bunny in blue
o3d.visualization.draw_geometries([bunny,bunny_scaled,bunny_rotate,bunny_transform])   #Zoom to see clearly

#5
o3d.io.write_point_cloud("data/bunny.pcd", bunny) 

Visualising point cloud.....
Visualising mesh.....
Converting to point cloud and visualising
Rotation Matrix: 
[[ 6.12323400e-17  0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17 -6.12323400e-17]
 [-6.12323400e-17  1.00000000e+00  3.74939946e-33]]
Transformation Matrix: 
[[ 6.12323400e-17  0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17 -6.12323400e-17  0.00000000e+00]
 [-6.12323400e-17  1.00000000e+00  3.74939946e-33  2.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


True

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

3. What is a Gimbal lock? 

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*


#3
A gimble is a ring which can spin about some axis. Multiple rotations can be achieved by introducing several rings placed such that they have a common center. Gimbles are used to measure angles.
A gimble lock is the loss of one degree of freedom in a 3D rotation. It occurs when the planes of some of the rings become parallel to each other, which leads to loss of dimensionality.

In [ ]:
import math
from scipy.optimize import fsolve

#1
def get_rotation_matrix(alpha,beta,gama):
    R = np.zeros((3,3))
    R[0,0] = math.cos(alpha)*math.cos(beta)
    R[0,1] = math.cos(alpha)*math.sin(beta)*math.sin(gama) - math.sin(alpha)*math.cos(gama) 
    R[0,2] = math.cos(alpha)*math.sin(beta)*math.cos(gama) + math.sin(alpha)*math.sin(gama)
    R[1,0] = math.sin(alpha)*math.cos(beta) 
    R[1,1] = math.sin(alpha)*math.sin(beta)*math.sin(gama) + math.cos(alpha)*math.cos(gama)
    R[1,2] = math.sin(alpha)*math.sin(beta)*math.cos(gama) - math.cos(alpha)* math.sin(gama)
    R[2,0] = -1*math.sin(beta)
    R[2,1] = math.cos(beta)*math.sin(gama)
    R[2,2] = math.cos(beta)*math.cos(gama)
    return R

#Given angles in radians
alpha = np.pi/2
beta = 0
gama = np.pi/6
R = get_rotation_matrix(alpha,beta,gama)
print(R)

#2
def func(angles, R):
    x = np.pi/2

    if R[2][0] == -1:
        eq_1 = angles[0]
        eq_2 = angles[1]-np.pi/2
        eq_3 = angles[2]-math.atan2(R[0][1], R[1][1])

    elif R[2][0] == 1:
        eq_1 = angles[0]
        eq_2 = angles[1]+np.pi/2
        eq_3 = angles[2]+math.atan2(R[0][1], R[1][1])

    else:
        eq_1 = angles[0]-math.atan2(R[1,0]/np.cos(angles[1]), R[0,0]/np.cos(angles[1]))
        eq_2 = angles[1]-math.atan2(-R[2,0], math.sqrt(R[0,0]*R[0,0]+R[1,0]*R[1,0]))
        eq_3 = angles[2]-math.atan2(R[2][1]/np.cos(angles[1]), R[2][2]/np.cos(angles[1]))

    return [eq_1,eq_2,eq_3]

def Solve_Angles(R):
    
    i1 = np.random.rand(1,3)
    angles1 = fsolve(func, i1, R)
    
    i2 = np.random.rand(1,3)
    angles2 = fsolve(func, i2, R)

    i3 = np.random.rand(1,3)
    angles3 = fsolve(func, i3, R)

    print("\n Initial [alpha,beta,gama] : ", i1,"\n Obtained [alpha,beta,gama] from i1: ", angles1)
    print("\n Initial [alpha,beta,gama] : ", i2,"\n Obtained [alpha,beta,gama] from i2: ", angles2)
    print("\n Initial [alpha,beta,gama]: ", i3,"\n Obtained [alpha,beta,gama] from i3: ", angles3)

    return angles1

M = np.array([[0.26200263,-0.19674724,0.944799],[0.21984631,0.96542533,0.14007684],[-0.93969262,0.17101007,0.29619813]])
N = np.array([[0,-0.173648178,0.984807753],[0,0.984807753,0.173648178],[-1,0,0]])

ang = Solve_Angles(M)
print("\n Angles corresponding to M:",ang,"\n")

ang = Solve_Angles(N)
print("\n Angles corresponding to N:",ang)


## b) Quaternions

1. What makes Quaternions popular in graphics? 
2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.
3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.
4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

#1
Using complex numbers/quaternions is a very natural way to encode geometric transformations in 2D, it simplifies the code and provides moderate reductions in computation and storage. The main usage of quaternions in computer graphics happens when a 3D character rotation is required. The method using quaternions allows a point/character to be rotated about multiple axes simultaneously, instead of sequentially multiplying matrix by a matrix as it happens in matrix rotation. For example, if you need to find the position of a point after rotating the frame along y = 2x line, then the point must first be rotated about the x-axis and then about the y-axis. This sequential process can be performed in ‘one-go’ by the quaternion method, it’s not really one go but still efficient, we’ll discuss the reason at the end. Also, this computation does not require the computation of trigonometric functions, only the addition and multiplication of real numbers is needed. Matrix rotations are inefficient because they suffer from what is known as Gimbal Lock. 
Gimbal lock is the loss of one degree of freedom in a three-dimensional, three-gimbal mechanism that occurs when the axes of two of the three gimbals are driven into a parallel configuration, "locking" the system into rotation in a degenerate two-dimensional space. This also contributes to less memory consumption and faster computation in quaternions.



In [24]:
#2 
def rotationToQuaternion(R):
  q0 = np.sqrt(1 + R[0][0] + R[1][1] + R[2][2])/2
  q1 = (R[2][1] - R[1][2])/(4 * q0)
  q2 = (R[0][2] - R[2][0])/(4 * q0)
  q3 = (R[1][0] - R[0][1])/(4 * q0)
  q = [q0, q1, q2, q3]
  return q

def quaternionToRotation(q):
  R = [[1 - 2*q[2]*q[2] - 2*q[3]*q[3], 2*q[1]*q[2] - 2*q[0]*q[3], 2*q[1]*q[3] + 2*q[0]*q[2]],
       [2*q[1]*q[2] + 2*q[0]*q[3], 1 - 2*q[1]*q[1] - 2*q[3]*q[3], 2*q[2]*q[3] - 2*q[0]*q[1]],
       [2*q[1]*q[3] - 2*q[0]*q[2], 2*q[2]*q[3] + 2*q[0]*q[1], 1 - 2*q[1]*q[1] - 2*q[2]*q[2]]]
  return R

def multiplyQuaternions(q, p):
  s = [q[0]*p[0] - q[1]*p[1] - q[2]*p[2] - q[3]*p[3], q[0]*p[1] + q[1]*p[0] + q[2]*p[3] - q[3]*p[2],
       q[0]*p[2] + q[2]*p[0] - q[1]*p[3] + q[3]*p[1], q[0]*p[3] + q[3]*p[0] + q[1]*p[2] - q[2]*p[1]]
  return s

R = np.array([[0.1,-0.9487,0.3],[0.9487,0.,-0.3162],[0.3,0.3162,0.9]])    #Matrix is taken from another question
q = rotationToQuaternion(R)
R_recover = quaternionToRotation(q)
print(R)
print(q)
print(R_recover)

[[ 0.1    -0.9487  0.3   ]
 [ 0.9487  0.     -0.3162]
 [ 0.3     0.3162  0.9   ]]
[0.7071067811865476, 0.2235871642111863, 0.0, 0.6708322033116776]
[[0.09996831000000017, -0.9487, 0.2999789399999999], [0.9487, -1.4129999999834553e-05, -0.3162], [0.2999789399999999, 0.3162, 0.90001756]]


In [25]:
#3
def rotationToQuaternion(R):
  q0 = np.sqrt(1 + R[0][0] + R[1][1] + R[2][2])/2
  q1 = (R[2][1] - R[1][2])/(4 * q0)
  q2 = (R[0][2] - R[2][0])/(4 * q0)
  q3 = (R[1][0] - R[0][1])/(4 * q0)
  q = [q0, q1, q2, q3]
  return q

def quaternionToRotation(q):
  R = [[1 - 2*q[2]*q[2] - 2*q[3]*q[3], 2*q[1]*q[2] - 2*q[0]*q[3], 2*q[1]*q[3] + 2*q[0]*q[2]],
       [2*q[1]*q[2] + 2*q[0]*q[3], 1 - 2*q[1]*q[1] - 2*q[3]*q[3], 2*q[2]*q[3] - 2*q[0]*q[1]],
       [2*q[1]*q[3] - 2*q[0]*q[2], 2*q[2]*q[3] + 2*q[0]*q[1], 1 - 2*q[1]*q[1] - 2*q[2]*q[2]]]
  return R

def multiplyQuaternions(q, p):
  s = [q[0]*p[0] - q[1]*p[1] - q[2]*p[2] - q[3]*p[3], q[0]*p[1] + q[1]*p[0] + q[2]*p[3] - q[3]*p[2],
       q[0]*p[2] + q[2]*p[0] - q[1]*p[3] + q[3]*p[1], q[0]*p[3] + q[3]*p[0] + q[1]*p[2] - q[2]*p[1]]
  return s

def multiplyRotations(A, B):
  C = np.dot(A, B)
  return C

def intervtQuaternion(q):
  p = [q[0], -q[1], -q[2], -q[3]]
  return p

R1 = np.array([[0.1,-0.9487,0.3],[0.9487,0.,-0.3162],[0.3,0.3162,0.9]])
R3 = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
R = multiplyRotations(R1, R3)
q1 = rotationToQuaternion(R1)
q2 = rotationToQuaternion(R3)
q = multiplyQuaternions(q1, q2)
R_recover = quaternionToRotation(q)

print(R)
print(R_recover)

[[-0.9487 -0.1     0.3   ]
 [ 0.     -0.9487 -0.3162]
 [ 0.3162 -0.3     0.9   ]]
[[-0.9487070650000001, -0.09997537500000032, 0.2999789399999999], [-7.064999999639721e-06, -0.9487070650000001, -0.3162], [0.31620000000000004, -0.29997893999999986, 0.90001756]]


In [26]:
#4
def multiplyQuaternions(q, p):
  s = [q[0]*p[0] - q[1]*p[1] - q[2]*p[2] - q[3]*p[3], q[0]*p[1] + q[1]*p[0] + q[2]*p[3] - q[3]*p[2],
       q[0]*p[2] + q[2]*p[0] - q[1]*p[3] + q[3]*p[1], q[0]*p[3] + q[3]*p[0] + q[1]*p[2] - q[2]*p[1]]
  return s

def multiplyRotations(A, B):
  C = np.dot(A, B)
  return C

def invertQuaternion(q):
  p = [q[0], -q[1], -q[2], -q[3]]
  return p
 
def slerp(q0, q1, t):
    q0_inv = invertQuaternion(q0)
    q2 = multiplyQuaternions(q0_inv, q1)
    q3 = quaternionPow(q2, t)
    q = multiplyQuaternions(q0, q3)
    return q


R1 = np.array([[0.1,-0.9487,0.3],[0.9487,0.,-0.3162],[0.3,0.3162,0.9]])
R2 = np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]])
R = multiplyRotations(R1, R2)
q1 = rotationToQuaternion(R1)
q2 = rotationToQuaternion(R2)
t = 0.1 # [0, 1]

q = slerp(q1, q2, t)

print(q1)
print(q2)
print(q)

NameError: name 'invertQuaternion' is not defined

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?
2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

#1
Exponential maps are an alternate to Rotation Matrix. We can visualise any rotation about an axis w(unit vector) and by an angle theta as an axis(along w) being rotated with some angular velocity 'w' for 'theta' seconds. 

Now assume we had a vector in initial frame called p. We need to find the final vector(say p_new) after frame rotation.
Now we can view p as it is being rotated about the given axis w, hence it proceeds to form a circle about the axis, we will write its tangential velocity as:

Using circular motion theory:
p_dot(t) = w x p(t) (cross product of w and p(t)) 
            , where p(t) = vector at time t, p_dot(t) = rate of change of vector's tip, w = angular velocity

It is a linear equation of vectors
We can view p_dot(t) = w x p(t) as:
p_dot(t) = [w_mat] p(t)  , where [w_mat] = skew_symmetric matrix of vector 'w'

So now the above equation is analogous to linear equation of scalars : x_dot(t) = k x(t), hence it's solution is also analogous to it.

Solution of p_dot(t) = [w_mat] p(t) is given by:

            p(t) = e^([w_mat]*theta) p(0)    
This can be compared to A = R*B , where R is rotational matrix(of B w.r.t A) and we go from B to A frame. Here we find p(t) given p(0).

Hence Rotational matrix R is analogous to e^([w_mat]*theta).

e^([w_mat]*theta) can be expanded and as w_mat is a skew symmetric matrix, the expansion simplifies to:
e^([w_mat]*theta) = I + sin(theta)[w_mat] + (1-cos(theta))[w_mat] 

So,
R = e^([w_mat]*theta) = I + sin(theta)[w_mat] + (1-cos(theta))[w_mat] 

In [17]:
#2 We will use Rodrigues' formula from above:

def exp_to_R(w,theta):
    I = np.eye(3)
    w_mat = np.array([[0,-w[2],w[1]],[w[2],0,-w[0]],[-w[1],w[0],0]])            #skew symmetric matrix corresponding to w vector
    R = I + math.sin(theta)*w_mat + (1-math.cos(theta))*(w_mat@w_mat)           #Rotation Matrix as defined in theory above
    return R

theta = 4.1364
w = np.array([2,1,15])
R = exp_to_R(w,theta)
print("Rotational Matrix is equal to: ")
print(R)
print("")

#3  We will need to find logarithm of rotation

def R_to_exp(R):
    if (R==np.eye(3)).all():
        return [0,"NA - w is not defined"]
    # As per JJ craig, we can convert R to [w,theta] as per last else condition, but there are corner cases (at theta=0 and theta=pi)
    # which are dealt with in 'if' and 'elif' 
    if np.trace(R)==-1:
        theta = np.pi
        if R[2,2]!=-1:
            w = (1/(np.sqrt(2*(1+R[2,2])))) * np.array([R[0,2],R[1,2],1+R[2,2]]) 
        elif R[1,1] != -1:
            w = (1/(np.sqrt(2*(1+R[1,1])))) * np.array([R[0,1],1+R[1,1],R[2,1]])
        else:
            w = (1/(np.sqrt(2*(1+R[0,0])))) * np.array([R[0,0],R[1,0],1+R[2,0]])            
        return [theta,w]
    theta = np.arccos(1/2*(np.trace(R)-1))
    w_hat = (1/(2*math.sin(theta))) * (R-R.transpose())
    w = ([w_hat[2,1],w_hat[0,2],w_hat[1,0]])
    return [theta,w]

R = np.array([[0.1,-0.9487,0.3],[0.9487,0.,-0.3162],[0.3,0.3162,0.9]])
[theta,w] = R_to_exp(R)
print("Angle of Rotation is: ")
print(theta)
print("Rotation vector is:")
print(w)

Rotational Matrix is equal to: 
[[-348.09417007   15.66913969   45.50128003]
 [  -9.49048181 -352.72816347   24.84727514]
 [  47.17858813   21.49265894   -6.72332235]]

Angle of Rotation is: 
1.5707963267948966
Rotation vector is:
[0.3162, 0.0, 0.9487]


# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?
2. When do we update an Octomap and why?
3. When would you likely use an octomap instead of a point cloud?
 

#1
A fixed-sized 3D mapping is not efficient because it doesn’t take into consideration the redundancies. Suppose we have 64 identical cubes of volume 1 cubic centimetre(all carry the same information), now we stack them in such a way that we form one cube side 8 cm, now how can we efficiently store the information of all the 64 cubes. One way could be to store the information in each cube separately, but that’s not optimum. The optimum way would be to store all the information present in the 64 small cubes in one 8 cm side cube, just because the information is the same throughout, this is what an Octomap does.
The Octomap uses an octree which is a tree basically. In an octree, at any position, a node represents a cube in the 3D space, if that cube has the same information throughout, it won’t have any child. If it has mixed information, say some cells are occupied while some aren’t, then the node further divides into 8 children (or 8 equal cubes), and this division process goes on until either all sub-cells are the same throughout the cell or when the highest resolution has been reached. This leads to a substantial reduction in the number of nodes that need to be maintained in the tree. Also besides being occupied, or not occupied, the cells can also be modelled as unknown space. 

#2
The more samples we have from an experiment the more sure we are about it. Octamap uses an extension of Bayes theorem and Markov assumption to determine the probability of the next state. This update formula depends on the current measurement, a prior probability, and the previous estimate, and it’s only performed on the leaf nodes because those are essentially the critical nodes. This update formula is applied when we change the Octomap’s position such that the new probability of the voxels can be fused with the earlier ones, If we try to update the probabilities without changing the position from where the data is taken, we’re not really providing the Octomap any new information.
All the samples are taken through the octomap in a local frame, hence very often a GPS is used to locate the mobile system, and then a transformation is performed whenever we update so that it can be made in the global frame. Another important feature of Octomap is that it can delay the initialization of the space until measurements need to be integrated. In this way, the extent of the mapped environment does not need to be known beforehand and the map only contains volumes that have been measured and hence we don’t need to update every cell each iteration.

#3
Point clouds store large amounts of measurement points and hence are not memory efficient. Moreover, the Point Cloud method has no provisions for modelling obstacle-free space and unknown areas and even for fusing multiple measurements probabilistically. Also, in this method sensor noise and dynamic objects cannot be incorporated directly. Hence, point clouds are only suitable for high precision sensors in static environments and when unknown areas do not need to be represented. Furthermore, the memory consumption of this representation increases with the number of measurements which is problematic as there is no upper bound. Consider the experiment of travelling along with modelling a forest through a robot. Since the robot would have to move, many measurements would be required and their probabilities need to be fused, along with detection of obstacle-free regions. Also since the forest is a large area, we would require more memory. None of the facts suggests using a point cloud method for this experiment, here Octamaps would be a good option.

## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?
2. How do we aggregate views from multiple cameras? (just a general overview is fine)
3. Which preserves details better? Voxels or SDF? Why?
4. What’s an advantage of SDF over a point cloud?


#1
The signed detection function also uses voxels to map the surroundings, but instead of storing the probability of occupancies, we store the distance of that voxel to the surface of the object. This distance is represented by a value that is given by the signed detection function. This value is negative when the voxel is outside the surface, it’s positive when it’s inside the surface, and it’s equal to zero when it's on the surface.

#2
Instead of storing the usual occupancy probability, a voxel stores 2 parameters, the distance and the weight.
A camera that has laser functionality in it which lets it measure the distance till which the laser could reach is used. A lot of beams are emitted from a single position, the angle between the beams is determined by the resolution, say m beams are emitted. All the voxels which come in the way of these m beams have their values updated. The distance to the surface can be calculated directly because we know the coordinates of the voxel and that of the camera, doing subtraction would give us the desired value. During the update, the distance and weight both are updated. The new distance is the weighted average over all previous measurements. Therefore, very often the weights are used as the number of observations. Now when we move to a different location, again m beams would be emitted and the voxels coming in their way would be updated. This way a cell very often comes in the way of many beams due to which its value gets updated.

#3
The signed-distance function also uses voxels but to store the distance from the surface and weight instead of occupancy probability. In SDF, we can customize our weighted approach, which can be the number of observations or something else depending on the implementation. Precise weighing based on the confidence of measurement can help us preserve details better.

#4
Point clouds store large amounts of measurement points and hence are not memory efficient. Moreover, the Point Cloud method has no provisions for modelling obstacle-free space and unknown areas. Whereas the SDF is memory efficient, it becomes even more efficient when we incorporate truncation in it, because with truncation we don’t store those values which are very huge in magnitude and don’t change much during iterations because they are very far from the surface. Also, since it shows the distance values, it gives a very good idea about where the obstruction/surface lies and hence can be used for that.

# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/